name: Java CI with JUnit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download JUnit Jupiter standalone
      run: |
        mkdir -p lib
        wget -O lib/junit-jupiter-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar

    - name: Clean previous builds
      run: find . -name "*.class" -type f -delete

    - name: Compile Java files
      run: |
        javac -cp .:src:test:lib/junit-jupiter-standalone.jar *.java src/*.java test/*.java

    - name: Run JUnit tests (JUnit 5)
      run: |
        java -jar lib/junit-jupiter-standalone.jar --class-path .:test --scan-class-path --details tree
      if: success() || failure()

    - name: Check test results
      run: |
        echo "Tests completed. Check logs above for results."