name: Java CI with Maven, JUnit and Jacoco

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Java 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '21'

    # 3. Cache de dependencias Maven
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 4. Compilar el proyecto
    - name: Build with Maven
      run: mvn clean compile

    # 5. Ejecutar tests y generar reportes JUnit + Jacoco
    - name: Run tests with Maven
      run: mvn test jacoco:report

    # 6. Subir reportes JUnit como artefactos
    - name: Upload JUnit test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-reports
        path: target/surefire-reports/

    # 7. Subir reportes de cobertura Jacoco como artefactos
    - name: Upload Jacoco coverage reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-reports
        path: target/site/jacoco/