name: Java CI with JUnit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download JUnit Jupiter standalone
      run: |
        mkdir -p lib
        wget -O lib/junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar

    - name: List files for debugging
      run: |
        echo "Estructura del proyecto:"
        find . -name "*.java" -type f | head -20
        echo "Total de archivos Java encontrados:"
        find . -name "*.java" -type f | wc -l

    - name: Find and compile all Java files
      run: |
        # Encontrar todos los archivos Java y compilarlos
        JAVA_FILES=$(find . -name "*.java" -type f)
        if [ -z "$JAVA_FILES" ]; then
          echo "No se encontraron archivos Java"
          exit 1
        fi
        echo "Compilando archivos:"
        echo "$JAVA_FILES"
        javac -cp .:lib/junit-platform-console-standalone.jar $JAVA_FILES

    - name: Run JUnit tests
      run: |
        # Ejecutar pruebas con detección automática
        java -jar lib/junit-platform-console-standalone.jar --class-path . --scan-class-path --details tree
      if: success() || failure()

    - name: Check test results
      run: |
        echo "Proceso de testing completado"